package com.boyan.ship.entity;
// Generated 2017-4-20 20:51:40 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbUser generated by hbm2java
 */
@Entity
@Table(name = "tb_user", catalog = "db_ship")
public class TbUser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String userId;
	private String loginName;
	private String pwd;
	private String name;
	private String sex;
	private String cardNo;
	private String department;
	private String mobile;
	private String email;
	private String roleId;
	private String state;

	public TbUser() {
	}

	public TbUser(String userId) {
		this.userId = userId;
	}

	public TbUser(String userId, String loginName, String pwd, String name, String sex, String cardNo,
			String department, String mobile, String email, String roleId, String state) {
		this.userId = userId;
		this.loginName = loginName;
		this.pwd = pwd;
		this.name = name;
		this.sex = sex;
		this.cardNo = cardNo;
		this.department = department;
		this.mobile = mobile;
		this.email = email;
		this.roleId = roleId;
		this.state = state;
	}

	@Id

	@Column(name = "userId", unique = true, nullable = false, length = 32)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "loginName", length = 32)
	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	@Column(name = "pwd", length = 32)
	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	@Column(name = "name", length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "sex", length = 2)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "cardNo", length = 32)
	public String getCardNo() {
		return this.cardNo;
	}

	public void setCardNo(String cardNo) {
		this.cardNo = cardNo;
	}

	@Column(name = "department", length = 32)
	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@Column(name = "mobile", length = 32)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "roleId", length = 32)
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	@Column(name = "state", length = 2)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
